name: Deploy New York Tropical Wood

on:
  push:
    branches:
      - main
    paths:
      - 'docs/new-york-tropical-wood/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Replace Mapbox token
      - name: Replace MAPBOX token in index.html
        run: |
          sed -i "s|__MAPBOX_TOKEN__|${{ secrets.MAPBOX_TOKEN }}|g" docs/new-york-tropical-wood/index.html

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/new-york-tropical-wood

