name: Prepare Mapbox Token

on:
  push:
    branches:
      - main
    paths:
      - 'docs/new-york-tropical-wood/**'

jobs:
  replace-token:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Replace Mapbox token placeholder
      - name: Replace MAPBOX token in map-integrated.js
        run: |
          sed -i "s|__MAPBOX_TOKEN__|${{ secrets.MAPBOX_TOKEN }}|g" docs/new-york-tropical-wood/map-integrated.js

      # Step 3: Verify replacement
      - name: Verify replacement
        run: |
          head -n 10 docs/new-york-tropical-wood/map-integrated.js
